=== Fuguety/College-UPSA/Programing2/src/main/java/college.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT college (classes)>
<!ELEMENT classes (class+)>
<!ELEMENT class (nameClass, credits, year, classType, students, teachers)>

<!ELEMENT nameClass (#PCDATA)>
<!ELEMENT credits (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT classType (#PCDATA)>


<!ELEMENT students (student+)>
<!ELEMENT student (name, surname, grades?)>
<!ATTLIST student nexpedient ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT grades (#PCDATA)>


<!ELEMENT teachers (teacher+)>
<!ELEMENT teacher (nameTeacher, surnameTeacher)>
<!ATTLIST teacher nif ID #REQUIRED>
<!ELEMENT nameTeacher (#PCDATA)>
<!ELEMENT surnameTeacher (#PCDATA)>

<!ELEMENT __ROOT__ ANY>
<!ATTLIST __ROOT__ version CDATA #REQUIRED>

=== Fuguety/College-UPSA/Programing2/src/main/java/college.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE college SYSTEM "college.dtd">


<college>
    
    <classes>
        <class>

            <nameClass>Programming 2</nameClass>
            <credits>6</credits>
            <year>1</year>
            <classType>Mandatory</classType>

            <students>

                <student nexpedient='_00001'>
                    <name>Neymar</name>
                    <surname>Jr</surname>
                    <grades>7</grades>
                </student>
                <student nexpedient='_00002'>
                    <name>Messi</name>
                    <surname>Soprando</surname>
                    <grades>10</grades>
                </student>
                <student nexpedient='_00003'>
                    <name>Felipe</name>
                    <surname>Massa</surname>
                    <grades>9</grades>
                </student>

            </students>

            <teachers>

                <teacher nif='_00000001a'>
                    <nameTeacher>Airton</nameTeacher>
                    <surnameTeacher>Senna</surnameTeacher>
                </teacher>
                <teacher nif='_00000002a'>
                    <nameTeacher>Jhonny</nameTeacher>
                    <surnameTeacher>Silverhand</surnameTeacher>
                </teacher>
            </teachers>
        </class>
        
        
        <class>

            <nameClass>Data Banks 2</nameClass>
            <credits>6</credits>
            <year>2</year>
            <classType>Mandatory</classType>

            <students>

                <student nexpedient='_00004'>
                    <name>Carlos</name>
                    <surname>Augustus</surname>
                    <grades>3</grades>
                </student>
                <student nexpedient='_00005'>
                    <name>Dom</name>
                    <surname>Pedro</surname>
                    <grades>10</grades>
                </student>
                <student nexpedient='_00006'>
                    <name>Felipe</name>
                    <surname>Montana</surname>
                    <grades>5</grades>
                </student>

            </students>

            <teachers>

                <teacher nif='_00000003a'>
                    <nameTeacher>Luis</nameTeacher>
                    <surnameTeacher>Lula</surnameTeacher>
                </teacher>
                <teacher nif='_00000004a'>
                    <nameTeacher>Jair</nameTeacher>
                    <surnameTeacher>Bolsonaro</surnameTeacher>
                </teacher>
            </teachers>
        </class>
        
        <class>

            <nameClass>Estatistics</nameClass>
            <credits>6</credits>
            <year>2</year>
            <classType>Oprional</classType>

            <students>

                <student nexpedient='_00007'>
                    <name>Dilma</name>
                    <surname>Rouseff</surname>
                    <grades>0</grades>
                </student>
                <student nexpedient='_00008'>
                    <name>Joe</name>
                    <surname>Biden</surname>
                    <grades>8</grades>
                </student>

            </students>

            <teachers>

                <teacher nif='_00000005a'>
                    <nameTeacher>Donald</nameTeacher>
                    <surnameTeacher>Trump</surnameTeacher>
                </teacher>
                
            </teachers>
        </class>

    </classes>
    
</college>
